sudo: required

language: python

install:
- pip install codecov

services:
- docker

before_script:
- docker-compose build
- docker-compose up -d

script:
- docker-compose run --rm server sh -c 'coverage run ./manage.py test api && coverage report'

after_script:
- docker-compose down

after_success:
- codecov

branches:
  only:
  - master