# Generated by Django 2.1.5 on 2019-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='replace_original_domain',
            field=models.BooleanField(default=False),
        ),
    ]
